network:
  driver_type: bridge
  name: swiftdeploy-network
nginx:
  image: nginx:latest
  port: 8080
  proxy_timeout: 30
services:
  image: swift-deploy-1-node:latest
  mode: stable
  port: 3000
  restart_policy: always
  version: 1.0.0
volumes:
  logs: swiftdeploy-logs
